-- Script generated by WinDev on 07/10/2017 00:21:18
-- Tables of Stock.wda analysis
-- for PostgreSQL

-- Deleting the Auditoria_eventos table
DROP TABLE "Auditoria_eventos" ;
-- Creating the Auditoria_eventos table
CREATE TABLE "Auditoria_eventos" (
    "AuditoriaID" SERIAL4  PRIMARY KEY ,
    "Descripción_evento" VARCHAR(256) ,
    "Tipo_evento" VARCHAR(25) ,
    "Usuario" VARCHAR(50) ,
    "fecha_evento" DATE );

-- Deleting the Auditoria_pedidos table
DROP TABLE "Auditoria_pedidos" ;
-- Creating the Auditoria_pedidos table
CREATE TABLE "Auditoria_pedidos" (
    "Estado" VARCHAR(20) DEFAULT NULL,
    "Tipo_de_asociado" VARCHAR(25) DEFAULT NULL,
    "Asociado" VARCHAR(50) DEFAULT NULL,
    "Cotizacion" NUMERIC(10,0) DEFAULT NULL,
    "Presupuesto" NUMERIC(10,0) DEFAULT NULL,
    "Cantidad" REAL DEFAULT NULL,
    "Descripción" VARCHAR(255) ,
    "Unidad" VARCHAR(5) DEFAULT NULL,
    "PedidoID" INTEGER DEFAULT NULL,
    "Elemento_Pedido_ID" VARCHAR(5)  UNIQUE ,
    "fecha_deposito" TIMESTAMP ,
    "fecha_aprobacion_gerencia" TIMESTAMP ,
    "fecha_aprobacion_OC_gerencia" TIMESTAMP ,
    "Supera_Precio_Cotizado" BOOL DEFAULT false,
    "Cotizado_o_no" SMALLINT DEFAULT 0,
    "Precio_Cotizado" NUMERIC(10,2) DEFAULT 0,
    "ProductoID" INTEGER DEFAULT 0,
    "Nom_Ape" VARCHAR(50) ,
    "Observaciones" TEXT ,
    "Fecha_Pedido" TIMESTAMP ,
    "Fecha_Entrega" DATE );
CREATE INDEX "WDIDX_Auditoria_pedidos_PedidoID" ON "Auditoria_pedidos" ("PedidoID");
CREATE INDEX "WDIDX_Auditoria_pedidos_ProductoID" ON "Auditoria_pedidos" ("ProductoID");

-- Deleting the Elem_del_Pedido table
DROP TABLE "Elemento_del_Pedido" ;
-- Creating the Elem_del_Pedido table
CREATE TABLE "Elemento_del_Pedido" (
    "Estado" VARCHAR(20) DEFAULT NULL,
    "Tipo_de_asociado" VARCHAR(25) DEFAULT NULL,
    "Asociado" VARCHAR(50) DEFAULT NULL,
    "Cotizacion" NUMERIC(10,0) DEFAULT NULL,
    "Presupuesto" NUMERIC(10,0) DEFAULT NULL,
    "Cantidad" REAL DEFAULT NULL,
    "Descripción" VARCHAR(255) ,
    "Unidad" VARCHAR(5) DEFAULT NULL,
    "PedidoID" INTEGER DEFAULT NULL,
    "Elemento_Pedido_ID" VARCHAR(5)  UNIQUE ,
    "fecha_deposito" TIMESTAMP ,
    "fecha_aprobacion_gerencia" TIMESTAMP ,
    "fecha_aprobacion_OC_gerencia" TIMESTAMP ,
    "Supera_Precio_Cotizado" BOOL DEFAULT false,
    "Cotizado_o_no" SMALLINT DEFAULT 0,
    "Precio_Cotizado" NUMERIC(10,2) DEFAULT 0,
    "ProductoID" INTEGER DEFAULT 0);
CREATE INDEX "WDIDX_Elem_del_Pedido_PedidoID" ON "Elemento_del_Pedido" ("PedidoID");
CREATE INDEX "WDIDX_Elem_del_Pedido_ProductoID" ON "Elemento_del_Pedido" ("ProductoID");

-- Deleting the Familia table
DROP TABLE "Familia" ;
-- Creating the Familia table
CREATE TABLE "Familia" (
    "Descripción" VARCHAR(128) DEFAULT NULL,
    "Codigo" INTEGER DEFAULT NULL,
    "IDFamilia" SERIAL4  PRIMARY KEY );

-- Deleting the Maquinas_y_Herramientas table
DROP TABLE "Maquinas_y_Herramientas" ;
-- Creating the Maquinas_y_Herramientas table
CREATE TABLE "Maquinas_y_Herramientas" (
    "Maqiunas_y_HerramientasID" SERIAL4  PRIMARY KEY ,
    "Denominacion_interna" VARCHAR(25) ,
    "Descripción" VARCHAR(50) ,
    "Tipo_de_asociadoID" NUMERIC(10,0) DEFAULT 0);
CREATE INDEX "WDIDX_Maquinas_y_Herramientas_Tipo_de_asociadoID" ON "Maquinas_y_Herramientas" ("Tipo_de_asociadoID");

-- Deleting the Pedido table
DROP TABLE "Pedido" ;
-- Creating the Pedido table
CREATE TABLE "Pedido" (
    "PedidoID" SERIAL4  PRIMARY KEY ,
    "Fecha_Pedido" TIMESTAMP DEFAULT NULL,
    "Nom_Ape" VARCHAR(50) DEFAULT NULL,
    "Fecha_Entrega" DATE ,
    "Observaciones" TEXT );

-- Deleting the Personal table
DROP TABLE "Personal" ;
-- Creating the Personal table
CREATE TABLE "Personal" (
    "Nom_Ape" VARCHAR(50) DEFAULT NULL,
    "Puesto" VARCHAR(25) DEFAULT NULL,
    "Sector" VARCHAR(25) DEFAULT NULL,
    "Clave" VARCHAR(6) DEFAULT NULL,
    "foto" BYTEA DEFAULT NULL,
    "Legajo" INTEGER  NOT NULL  UNIQUE  DEFAULT 0,
    "Activo" BOOL  NOT NULL  DEFAULT false,
    "Dirección" TEXT DEFAULT NULL,
    "Provincia" VARCHAR(25) DEFAULT NULL,
    "Localidad" VARCHAR(50) DEFAULT NULL,
    "Tipo_AsociadoID" INTEGER ,
    "Tipo_de_asociadoID" NUMERIC(10,0) );
CREATE INDEX "WDIDX_Personal_Tipo_AsociadoID" ON "Personal" ("Tipo_AsociadoID");
CREATE INDEX "WDIDX_Personal_Tipo_de_asociadoID" ON "Personal" ("Tipo_de_asociadoID");

-- Deleting the Producto table
DROP TABLE "Producto" ;
-- Creating the Producto table
CREATE TABLE "Producto" (
    "ProductoID" SERIAL4  PRIMARY KEY ,
    "Descripción" VARCHAR(128)  UNIQUE  DEFAULT NULL,
    "Familia" VARCHAR(50) DEFAULT NULL,
    "Unidad" VARCHAR(5) DEFAULT NULL,
    "Activo" BOOL DEFAULT NULL,
    "Plan_de_cuentas" VARCHAR(50) DEFAULT NULL,
    "Stock_minimo" FLOAT8 DEFAULT NULL,
    "Stock_medio" FLOAT8 DEFAULT NULL,
    "Costo" VARCHAR(50) DEFAULT NULL,
    "Observaciones" TEXT DEFAULT NULL);

-- Deleting the Subcuentas table
DROP TABLE "Subcuentas" ;
-- Creating the Subcuentas table
CREATE TABLE "Subcuentas" (
    "ProveedoresID" SERIAL4  PRIMARY KEY ,
    "Razón_Social" VARCHAR(50) DEFAULT NULL,
    "Dirección" TEXT DEFAULT NULL,
    "Localidad" VARCHAR(50) DEFAULT NULL,
    "Provincia" VARCHAR(25) DEFAULT NULL,
    "CUIT_CUIL" VARCHAR(20)  UNIQUE  DEFAULT NULL,
    "CBU" VARCHAR(40) DEFAULT NULL,
    "C_Postal" VARCHAR(10) DEFAULT NULL,
    "Telefono" VARCHAR(50) DEFAULT NULL,
    "Email" VARCHAR(50) DEFAULT NULL,
    "Activo" BOOL DEFAULT NULL,
    "Ingresos_Brutos" VARCHAR(20) DEFAULT NULL,
    "Observaciones" TEXT DEFAULT NULL,
    "Tipo_de_asociadoID" NUMERIC(10,0) );
CREATE INDEX "WDIDX_Subcuentas_Tipo_de_asociadoID" ON "Subcuentas" ("Tipo_de_asociadoID");

-- Deleting the Tipo_de_asociado table
DROP TABLE "Tipo_de_asociado" ;
-- Creating the Tipo_de_asociado table
CREATE TABLE "Tipo_de_asociado" (
    "Tipo_de_asociadoID" NUMERIC(10,0)  NOT NULL  UNIQUE  DEFAULT 0,
    "Descripción" VARCHAR(25) );

-- Deleting the Unidad table
DROP TABLE "Unidad" ;
-- Creating the Unidad table
CREATE TABLE "Unidad" (
    "Descripción" VARCHAR(128) DEFAULT NULL,
    "Abreviatura" VARCHAR(3) DEFAULT NULL,
    "IDUnidad" SERIAL4  PRIMARY KEY );
-- Integrity Constraints
ALTER TABLE "Elemento_del_Pedido" ADD FOREIGN KEY ("PedidoID") REFERENCES "Pedido" ("PedidoID");
ALTER TABLE "Maquinas_y_Herramientas" ADD FOREIGN KEY ("Tipo_de_asociadoID") REFERENCES "Tipo_de_asociado" ("Tipo_de_asociadoID");
ALTER TABLE "Subcuentas" ADD FOREIGN KEY ("Tipo_de_asociadoID") REFERENCES "Tipo_de_asociado" ("Tipo_de_asociadoID");
ALTER TABLE "Personal" ADD FOREIGN KEY ("Tipo_de_asociadoID") REFERENCES "Tipo_de_asociado" ("Tipo_de_asociadoID");
